sparql/urls.py
from django.conf.urls import url
from . import views

app_name = 'sparql'


urlpatterns = [
    url(r'^query/$', views.QueryView.as_view(), name='query'),
    url(r'^tunnel/$', views.query_tunnel, name='tunnel'),
]

sparql/models.py
from SPARQLWrapper import SPARQLWrapper, JSON
from django.conf import settings
from django.db import models

endpoint = getattr(settings, 'BG_URL', "https://no-endpoint.provided")


class SparqlConfig(models.Model):
    """Stores the URL of a SPARQL-Endpoint"""
    endpoint = models.CharField(default=endpoint, max_length=100)

    def __str__(self):
        return "{}".format(self.endpoint)


class Query(models.Model):
    """Stores sparql-queries"""
    endpoint = models.ForeignKey(
        SparqlConfig, blank=True, null=True, on_delete=models.PROTECT
    )
    query = models.TextField(blank=True, null=True)
    title = models.CharField(default="An example Query", max_length=200)
    description = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.endpoint is None:
            temp_endpoint, _ = SparqlConfig.objects.get_or_create(endpoint=endpoint)
            self.endpoint = temp_endpoint
        else:
            pass
        super(Query, self).save(*args, **kwargs)

    def get_rdf(self, *args, **kwargs):
        sparql = SPARQLWrapper(self.endpoint.endpoint)
        sparql.setQuery(self.query)
        sparql.setReturnFormat(JSON)
        results = sparql.query().convert()
        return results['bindings']

    def __str__(self):
        return "{}".format(self.title)

sparql/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class QueryForm(forms.Form):
    query = forms.CharField(
        required=False,
        widget=forms.Textarea()
    )

    def __init__(self, *args, **kwargs):
        super(QueryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'

sparql/views.py
from django.conf import settings
from SPARQLWrapper import SPARQLWrapper, JSON, BASIC
from django.http import JsonResponse
from django.http import Http404
from django.conf import settings
from django.shortcuts import render
from django.views.generic.edit import FormView
from .forms import QueryForm
from .models import Query


endpoint = getattr(settings, 'BG_URL', None)
bg_user = getattr(settings, 'BG_USER', None)
bg_pw = getattr(settings, 'BG_PW', None)


def query_tunnel(request):
    query = request.GET.get('query')
    sparql = SPARQLWrapper(endpoint)
    if bg_user and bg_pw:
        sparql.setHTTPAuth(BASIC)
        sparql.setCredentials(bg_user, bg_pw)
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()
    return JsonResponse(results, safe=False)


class QueryView(FormView):
    template_name = 'sparql/query_view.html'
    form_class = QueryForm
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(QueryView, self).get_context_data(**kwargs)
        context['examples'] = Query.objects.all()
        context['endpoint'] = endpoint
        return context

    def form_valid(self, form, **kwargs):
        context = self.get_context_data()
        cd = form.cleaned_data
        query = cd['query']
        context['query'] = query
        sparql = SPARQLWrapper(endpoint)
        print(endpoint)
        try:
            sparql.setQuery(query)
            sparql.setReturnFormat(JSON)
            results = sparql.query().convert()
            context['results'] = results['results']
            return render(self.request, self.template_name, context)
        except Exception as e:
            raise Http404("Bad Query: {}".format(e))

sparql/templates/sparql/query_view.html
{% extends "webpage/base.html" %}
{% block title %} SPARQL {% endblock %}
{% block content %}
    <div class="container">
        <h1 style="text-align:center">SPARQL Endpoint</h1>
        {% if examples %}
            <div id="examples">
                <h3>Example queries</h3>
                <hr/>
                {% for x in examples %}
                    <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#see-example-{{ x.id }}" id="see-example-btn-{{ x.id }}">
                        {{ x.title }}
                    </button>
                    <div id="see-example-{{ x.id }}" class="collapse">
                        <h5>{{ x.title }}: {{ x.description }}</h5>
                        <code>{{ x.query }}</code>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <div id="yasgui" style="padding: 2px;"></div>
        <link href="https://cdn.jsdelivr.net/npm/yasgui@2.7.19/dist/yasgui.min.css" rel="stylesheet" type="text/css">
        <style>
            .yasgui .endpointText {display:none !important;}
            .controlbar {display:none !important;}
        </style>
        <script src="https://cdn.jsdelivr.net/npm/yasgui@2.7.19/dist/yasgui.min.js"></script>
        <script type="text/javascript">
            var yasgui = YASGUI(document.getElementById("yasgui"), {
                yasqe: {
                    sparql: {
                        showQueryButton: true,
                        endpoint: "{% url 'sparql:tunnel' %}",
                        requestMethod: 'GET'
                    }
                }
              });
        </script>
    </div>
{% endblock %}